## 2.1 Arrays via numpy

In [2]:
# Intro NumPy arrays
import numpy as np
# Création d'arrays
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
# Arrays spéciaux
zeros = np.zeros((3, 4)) # Matrice de zéros
ones = np.ones((2, 3)) # Matrice de uns
identity = np.eye(3) # Matrice identité
random_arr = np.random.rand(2, 3) # Valeurs aléatoires [0,1)
print("Array 1D:", arr1d)
print("Shape:", arr1d.shape)
print("Type:", arr1d.dtype)

Array 1D: [1 2 3 4 5]
Shape: (5,)
Type: int64


In [3]:
## Indexation and slicing
# Array 1D
arr = np.array([10, 20, 30, 40, 50])
print("Premier élément:", arr[0])
print("Dernier élément:", arr[-1])
print("Sous-array:", arr[1:4])
# Array 2D
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Élément (1,2):", matrix[1, 2])
print("Première ligne:", matrix[0, :])
print("Deuxième colonne:", matrix[:, 1])
print("Sous-matrice:", matrix[0:2, 1:3])
# Indexation booléenne
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print("Éléments > 3:", arr[mask])

Premier élément: 10
Dernier élément: 50
Sous-array: [20 30 40]
Élément (1,2): 6
Première ligne: [1 2 3]
Deuxième colonne: [2 5 8]
Sous-matrice: [[2 3]
 [5 6]]
Éléments > 3: [4 5]


In [4]:
## Extraction and reshaping
# Reshape - changer les dimensions sans modifier les données
arr = np.arange(12) # [0, 1, 2, ..., 11]
reshaped = arr.reshape(3, 4)
print("Original:", arr)
print("Reshaped (3x4):\n", reshaped)
# Flatten - convertir en 1D
flattened = reshaped.flatten()
print("Flattened:", flattened)
# Transpose
transposed = reshaped.T
print("Transposed:\n", transposed)
# Extraction avec conditions
data = np.random.randint(0, 10, (4, 5))
print("Ceci est data :", data)
# Extraire les éléments pairs
even_elements = data[data % 2 == 0]
print("Éléments pairs:", even_elements)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Ceci est data : [[8 3 3 7 7]
 [1 0 9 5 9]
 [5 6 1 6 2]
 [9 7 6 2 9]]
Éléments pairs: [8 0 6 6 2 6 2]


In [5]:
## Multidimensional Arrays
# Array 3D : par exemple des images couleur (hauteur, largeur, canaux)
array_3d = np.zeros((10, 20, 3)) # 10×20 pixels, 3 canaux (RGB)
print("Shape 3D:", array_3d.shape)
# Array 4D : par exemple un batch d'images
array_4d = np.random.rand(32, 64, 64, 3) # 32 images de 64×64 pixels en couleur
print("Shape 4D:", array_4d.shape)
# Création avec arange et reshape
array_3d_example = np.arange(24).reshape(2, 3, 4)
print("Array 3D créé avec arange:")
print(array_3d_example)

Shape 3D: (10, 20, 3)
Shape 4D: (32, 64, 64, 3)
Array 3D créé avec arange:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [6]:
## Axis Parameter
# Exemple avec une matrice 3×4
matrix = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])
# Sommes selon différents axes
print("Matrice originale:")
print(matrix)
print("Shape:", matrix.shape) # (3, 4)
# axis=0 : somme le long des lignes (collapse les lignes)
sum_axis0 = np.sum(matrix, axis=0)
print("\nSomme axis=0 (par colonne):", sum_axis0)
print("Shape résultat:", sum_axis0.shape) # (4,)
# axis=1 : somme le long des colonnes (collapse les colonnes)
sum_axis1 = np.sum(matrix, axis=1)
print("Somme axis=1 (par ligne):", sum_axis1)
print("Shape résultat:", sum_axis1.shape) # (3,)
# axis=None : somme de tous les éléments
sum_all = np.sum(matrix)
print("Somme totale:", sum_all)

Matrice originale:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)

Somme axis=0 (par colonne): [15 18 21 24]
Shape résultat: (4,)
Somme axis=1 (par ligne): [10 26 42]
Shape résultat: (3,)
Somme totale: 78


## Exercice 1

In [7]:
# 1. Créez un array 3D de dimensions 4×5×6 contenant les entiers de 0 à 119. Dans quel ordre se remplissent les éléments ?
array_3d = np.arange(120).reshape(4, 5, 6)
print(array_3d)

[[[  0   1   2   3   4   5]
  [  6   7   8   9  10  11]
  [ 12  13  14  15  16  17]
  [ 18  19  20  21  22  23]
  [ 24  25  26  27  28  29]]

 [[ 30  31  32  33  34  35]
  [ 36  37  38  39  40  41]
  [ 42  43  44  45  46  47]
  [ 48  49  50  51  52  53]
  [ 54  55  56  57  58  59]]

 [[ 60  61  62  63  64  65]
  [ 66  67  68  69  70  71]
  [ 72  73  74  75  76  77]
  [ 78  79  80  81  82  83]
  [ 84  85  86  87  88  89]]

 [[ 90  91  92  93  94  95]
  [ 96  97  98  99 100 101]
  [102 103 104 105 106 107]
  [108 109 110 111 112 113]
  [114 115 116 117 118 119]]]


In [8]:
# 2. Extrayez le sous-array [1:3, 2:4, :] (lignes 1-2, colonnes 2-3, toutes les “profondeurs”)

sous_array = array_3d[:, 0:2, 1:3]
print("Sous-array:")
print(sous_array)

Sous-array:
[[[ 1  2]
  [ 7  8]]

 [[31 32]
  [37 38]]

 [[61 62]
  [67 68]]

 [[91 92]
  [97 98]]]


In [9]:
# 3. Calculez la moyenne selon chaque axe (0, 1, 2) et expliquez la forme des résultats
# axis=0 : somme le long des profondeurs (collapse des profondeurs)
mean_axis0 = np.mean(array_3d, axis=0)
print("\nMoyenne axis=0:", mean_axis0)
print("Shape résultat:", mean_axis0.shape)
# axis=1 : somme le long des lignes (collapse les lignes)
mean_axis1 = np.mean(array_3d, axis=1)
print("Moyenne axis=1:", mean_axis1)
print("Shape résultat:", mean_axis1.shape)
# axis=2 : somme le long des collones (collapse des collones)
mean_axis2 = np.mean(array_3d, axis=2)
print("Moyenne axis=2:", mean_axis2)
print("Shape résultat:", mean_axis2.shape)


Moyenne axis=0: [[45. 46. 47. 48. 49. 50.]
 [51. 52. 53. 54. 55. 56.]
 [57. 58. 59. 60. 61. 62.]
 [63. 64. 65. 66. 67. 68.]
 [69. 70. 71. 72. 73. 74.]]
Shape résultat: (5, 6)
Moyenne axis=1: [[ 12.  13.  14.  15.  16.  17.]
 [ 42.  43.  44.  45.  46.  47.]
 [ 72.  73.  74.  75.  76.  77.]
 [102. 103. 104. 105. 106. 107.]]
Shape résultat: (4, 6)
Moyenne axis=2: [[  2.5   8.5  14.5  20.5  26.5]
 [ 32.5  38.5  44.5  50.5  56.5]
 [ 62.5  68.5  74.5  80.5  86.5]
 [ 92.5  98.5 104.5 110.5 116.5]]
Shape résultat: (4, 5)


In [10]:
# 4. Trouvez les indices des éléments supérieurs à 100 avec np.where
sup_cent = np.where(array_3d >= 100)
print(sup_cent)

(array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]), array([1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4]), array([4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]))


In [11]:
# 5. Redimensionnez l’array original en format 10×12
reshaped = array_3d.reshape(10, 12)
print("Reshaped (10x12):\n", reshaped)

Reshaped (10x12):
 [[  0   1   2   3   4   5   6   7   8   9  10  11]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]
 [ 24  25  26  27  28  29  30  31  32  33  34  35]
 [ 36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79  80  81  82  83]
 [ 84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107]
 [108 109 110 111 112 113 114 115 116 117 118 119]]


## 2.2 Calculs vectoriels et matriciels

In [12]:
# Opérations scalaires
arr = np.array([1, 2, 3, 4, 5])
# Opérations arithmétiques
result1 = arr + 10 # Addition scalaire
result2 = arr * 2 # Multiplication scalaire
result3 = arr ** 2 # Élévation au carré
result4 = np.sqrt(arr) # Racine carrée
print("Original:", arr)
print("+ 10:", result1)
print("× 2:", result2)
print("Carré:", result3)
print("Racine:", result4)
# Fonctions mathématiques
angles = np.array([0, np.pi/4, np.pi/2, np.pi])
sin_values = np.sin(angles)
cos_values = np.cos(angles)
exp_values = np.exp(arr)
log_values = np.log(arr)

Original: [1 2 3 4 5]
+ 10: [11 12 13 14 15]
× 2: [ 2  4  6  8 10]
Carré: [ 1  4  9 16 25]
Racine: [1.         1.41421356 1.73205081 2.         2.23606798]


In [13]:
# Opérations vectorielles
# Opérations élément par élément
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
addition = a + b # [6, 8, 10, 12]
multiplication = a * b # [5, 12, 21, 32]
division = a / b # [0.2, 0.33, 0.43, 0.5]
# Produit scalaire
dot_product = np.dot(a, b) # ou a @ b
print("Produit scalaire:", dot_product)
# Norme d'un vecteur
norm = np.linalg.norm(a)
print("Norme euclidienne:", norm)
# Opérations de réduction
somme = np.sum(a)
moyenne = np.mean(a)
maximum = np.max(a)
minimum = np.min(a)

Produit scalaire: 70
Norme euclidienne: 5.477225575051661


In [14]:
# Opérations matricielles
# Matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
# Multiplication matricielle
C = A @ B # ou np.dot(A, B)
print("A @ B:\n", C)
# Transposée
A_T = A.T
print("Transposée de A:\n", A_T)
# Déterminant
det_A = np.linalg.det(A)
print("Déterminant de A:", det_A)
# Inverse (si elle existe)
if det_A != 0:
    A_inv = np.linalg.inv(A)
    print("Inverse de A:\n", A_inv)
    # Vérification : A @ A^(-1) = I
    identity_check = A @ A_inv
    print("A @ A^(-1):\n", identity_check)
# Valeurs propres et vecteurs propres
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Valeurs propres:", eigenvalues)
print("Vecteurs propres:\n", eigenvectors)
# Opérations par axe sur les matrices
matrix = np.random.rand(4, 3)
sum_rows = np.sum(matrix, axis=1) # Somme par ligne
sum_cols = np.sum(matrix, axis=0) # Somme par colonne
mean_all = np.mean(matrix) # Moyenne globale

A @ B:
 [[19 22]
 [43 50]]
Transposée de A:
 [[1 3]
 [2 4]]
Déterminant de A: -2.0000000000000004
Inverse de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
A @ A^(-1):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
Valeurs propres: [-0.37228132  5.37228132]
Vecteurs propres:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [15]:
# Broadcasting
# Broadcasting avec scalaire
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = arr + 10 # Le scalaire est diffusé sur tout l'array
# Broadcasting avec vecteurs
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_vector = np.array([10, 20, 30])
col_vector = np.array([[1], [2], [3]])
# Addition ligne par ligne
result1 = matrix + row_vector
print("Matrix + row_vector:\n", result1)
# Addition colonne par colonne
result2 = matrix + col_vector
print("Matrix + col_vector:\n", result2)

Matrix + row_vector:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
Matrix + col_vector:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


## Exercice 2

In [16]:
A = np.random.uniform(-2,2, (5, 4))
print(A)

[[ 1.13252035  1.67878298 -1.07182667  0.88938868]
 [ 0.06975577  1.51898669  0.97146236 -1.19406162]
 [-0.82565738 -0.78504604 -0.25059748 -0.21976564]
 [-1.11197602  1.18983945  0.85805598  1.86589771]
 [ 0.07973654  0.80494282  1.71674314  0.41923226]]


In [17]:
# 1. Calculez la norme euclidienne de chaque ligne et chaque colonne
norm_colonne = np.linalg.norm(A,axis=0)
norm_ligne = np.linalg.norm(A,axis=1)
print(norm_colonne)
print(norm_ligne)

[1.79221285 2.79384699 2.41636456 2.43360274]
[2.45779155 2.16372565 1.18705662 2.62107667 1.94351577]


In [18]:
# 2. Centrez la matrice (soustraire la moyenne de chaque colonne)
moyenne_colonne = np.mean(A,axis=0)
print(moyenne_colonne)

[-0.13112415  0.88150118  0.44476746  0.35213828]


In [19]:
# 3. Calculez la matrice de covariance des colonnes
B = np.cov(A)

In [20]:
# 4. Effectuez une décomposition en valeurs singulières (SVD) avec np.linalg.svd
C = np.linalg.svd(A)
D = np.linalg.svd(B)

In [21]:
# 5. Utilisez différents axes pour calculer les statistiques (mean, std, min, max)
moyenne_colonne = np.mean(A,axis=0)
moyenne_ligne = np.mean(A,axis=1)
std_colonne = np.std(A,axis=0)
std_ligne = np.std(A,axis=1)
min_colonne = np.min(A,axis=0)
min_ligne = np.min(A,axis=1)
max_colonne = np.max(A,axis=0)
max_ligne = np.max(A,axis=1)

## 2.3 Supplément : Manipulation de dates et date-heures

In [22]:
# Introduction à Pandas pour les dates
import pandas as pd
from datetime import datetime, timedelta
import numpy as np
# Création de dates
date_str = "2023-01-15"
date_obj = pd.to_datetime(date_str)
print("Date:", date_obj)
print("Type:", type(date_obj))
# Plages de dates
dates_range = pd.date_range(start='2023-01-01', end='2023-12-31', freq='D')
print("Nombre de jours en 2023:", len(dates_range))
# Plages avec fréquences différentes
monthly = pd.date_range(start='2023-01-01', periods=12, freq='M')
weekly = pd.date_range(start='2023-01-01', periods=52, freq='W')
hourly = pd.date_range(start='2023-01-01', periods=24, freq='H')
print("Dates mensuelles:", monthly[:3])

Date: 2023-01-15 00:00:00
Type: <class 'pandas._libs.tslibs.timestamps.Timestamp'>
Nombre de jours en 2023: 365
Dates mensuelles: DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31'], dtype='datetime64[ns]', freq='ME')


C:\Users\thiba\AppData\Local\Temp\ipykernel_4476\4111916948.py:14: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly = pd.date_range(start='2023-01-01', periods=12, freq='M')
C:\Users\thiba\AppData\Local\Temp\ipykernel_4476\4111916948.py:16: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = pd.date_range(start='2023-01-01', periods=24, freq='H')


In [23]:
# Manipulation et calculs de durées
# Calculs de durées
start_date = pd.to_datetime('2023-01-01')
end_date = pd.to_datetime('2023-12-31')
duration = end_date - start_date
print("Durée:", duration)
print("Jours:", duration.days)
# Opérations sur les dates
date = pd.to_datetime('2023-06-15')
one_week_later = date + pd.Timedelta(weeks=1)
one_month_ago = date - pd.DateOffset(months=1)
print("Date originale:", date)
print("Une semaine plus tard:", one_week_later)
print("Un mois plus tôt:", one_month_ago)
# Extraction d'informations temporelles
dates = pd.date_range('2023-01-01', periods=365, freq='D')
df = pd.DataFrame({'date': dates})
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['weekday'] = df['date'].dt.day_name()
df['quarter'] = df['date'].dt.quarter
print("Premiers enregistrements:")
print(df.head())

Durée: 364 days 00:00:00
Jours: 364
Date originale: 2023-06-15 00:00:00
Une semaine plus tard: 2023-06-22 00:00:00
Un mois plus tôt: 2023-05-15 00:00:00
Premiers enregistrements:
        date  year  month  day    weekday  quarter
0 2023-01-01  2023      1    1     Sunday        1
1 2023-01-02  2023      1    2     Monday        1
2 2023-01-03  2023      1    3    Tuesday        1
3 2023-01-04  2023      1    4  Wednesday        1
4 2023-01-05  2023      1    5   Thursday        1


In [24]:
# Changement d’unités temporelles
# Conversion entre unités
duree_seconds = 3661 # secondes
duree_timedelta = pd.Timedelta(seconds=duree_seconds)
print("Durée en secondes:", duree_seconds)
print("En heures:", duree_timedelta.total_seconds() / 3600)
print("En minutes:", duree_timedelta.total_seconds() / 60)
print("Format lisible:", duree_timedelta)
# Travail avec des timestamps
timestamps = pd.to_datetime(['2023-01-01 10:30:00',
'2023-01-01 14:45:30',
'2023-01-02 09:15:45'])
# Conversion en différents fuseaux horaires
timestamps_utc = timestamps.tz_localize('UTC')
timestamps_paris = timestamps_utc.tz_convert('Europe/Paris')
print("UTC:", timestamps_utc[0])
print("Paris:", timestamps_paris[0])
# Arrondi temporel
dates_high_freq = pd.date_range('2023-01-01', periods=100, freq='17min')
dates_hourly = dates_high_freq.round('H') # Arrondi à l'heure
dates_daily = dates_high_freq.round('D') # Arrondi au jour
print("Fréquence originale:", dates_high_freq[:3])
print("Arrondi horaire:", dates_hourly[:3])
print("Arrondi quotidien:", dates_daily[:3])

Durée en secondes: 3661
En heures: 1.0169444444444444
En minutes: 61.016666666666666
Format lisible: 0 days 01:01:01
UTC: 2023-01-01 10:30:00+00:00
Paris: 2023-01-01 11:30:00+01:00
Fréquence originale: DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 00:17:00',
               '2023-01-01 00:34:00'],
              dtype='datetime64[ns]', freq='17min')
Arrondi horaire: DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 00:00:00',
               '2023-01-01 01:00:00'],
              dtype='datetime64[ns]', freq=None)
Arrondi quotidien: DatetimeIndex(['2023-01-01', '2023-01-01', '2023-01-01'], dtype='datetime64[ns]', freq=None)


C:\Users\thiba\AppData\Local\Temp\ipykernel_4476\565487094.py:20: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates_hourly = dates_high_freq.round('H') # Arrondi à l'heure


In [25]:
# Analyse temporelle
# Séries temporelles avec indexation par date
np.random.seed(42)
dates = pd.date_range('2023-01-01', periods=365, freq='D')
values = np.cumsum(np.random.randn(365))
ts = pd.Series(values, index=dates)
# Sélection par date
janvier = ts['2023-01']
print("Données de janvier:", len(janvier))
# Rééchantillonnage
ts_monthly = ts.resample('M').mean() # Moyenne mensuelle
ts_weekly = ts.resample('W').sum() # Somme hebdomadaire
print("Moyennes mensuelles:")
print(ts_monthly.head())
# Calcul de variations
ts_diff = ts.diff() # Différences jour à jour
ts_pct_change = ts.pct_change() # Variation en pourcentage
# Fenêtres glissantes
ts_rolling_mean = ts.rolling(window=7).mean() # Moyenne mobile sur 7 jours
ts_rolling_std = ts.rolling(window=30).std() # Écart-type mobile sur 30 jours

Données de janvier: 31
Moyennes mensuelles:
2023-01-31    -0.476065
2023-02-28    -8.790241
2023-03-31    -9.179280
2023-04-30   -10.880120
2023-05-31   -10.460635
Freq: ME, dtype: float64


C:\Users\thiba\AppData\Local\Temp\ipykernel_4476\168616431.py:11: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  ts_monthly = ts.resample('M').mean() # Moyenne mensuelle


## Exercice 3

In [26]:
# 1. Créez une série temporelle avec des ventes aléatoires (entre 100 et 1000€) pour chaque jour avec le code
import pandas as pd
import numpy as np
# Configuration pour reproductibilité
np.random.seed(42)
# Créer la plage de dates
dates = pd.date_range(start='2022-01-01', end='2023-12-31', freq='D')
# Générer des ventes aléatoires avec tendance saisonnière
# Base: 500€ + tendance + saisonnalité + bruit
trend = np.linspace(0, 100, len(dates)) # Tendance croissante
seasonal = 200 * np.sin(2 * np.pi * np.arange(len(dates)) / 365.25) # Cycle annuel
noise = np.random.normal(0, 50, len(dates)) # Bruit
ventes_base = 500 + trend + seasonal + noise
# S'assurer que les ventes sont entre 100 et 1000
ventes = np.clip(ventes_base, 100, 1000)
# Créer la série temporelle
ventes_ts = pd.Series(ventes, index=dates, name='ventes')

In [27]:
# 2. Calculez les ventes mensuelles totales
janv = np.sum(ventes_ts['2022-01-01':'2022-01-31', :])

KeyError: 'key of type tuple not found and not a MultiIndex'